language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - sudo pip install codecov

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - ./vendor/bin/phpcs --standard=psr2 ./src
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - codecov

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
